apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-kubernetes.yaml
configMapGenerator:
  - name: enterprise-doc-prometheus-config
    files:
      - prometheus.yml=prometheus-kubernetes.yml
      - enterprise-doc-agent.rules.yml=rules/enterprise-doc-agent.rules.yml
generatorOptions:
  disableNameSuffixHash: true
