/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 71152cb6d32249fccd4ca1e7891b0431)
interface __BaseEnv_Env {
	MONITOR_DB: D1Database;
	MAIL: SendEmail;
	TARGET_URL: string;
	MONITOR_KEY: string;
	MODE: string;
	DRILL_START_MS: string;
	CHECK_READINESS: string;
	QUEUE_HEARTBEAT_KEY: string;
	BACKUP_HEARTBEAT_KEY: string;
	WATCH_MONITOR_KEY: string;
	MAIL_FROM: string;
	MAIL_TO: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./monitor");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TARGET_URL" | "MONITOR_KEY" | "MODE" | "DRILL_START_MS" | "CHECK_READINESS" | "QUEUE_HEARTBEAT_KEY" | "BACKUP_HEARTBEAT_KEY" | "WATCH_MONITOR_KEY" | "MAIL_FROM" | "MAIL_TO">> {}
}
