/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: a45dcdfd7ae43dc4d3c55049103bf660)
interface __BaseEnv_Env {
	MONITOR_DB: D1Database;
	MAIL: SendEmail;
	TARGET_URL: string;
	MONITOR_KEY: string;
	MODE: string;
	DRILL_START_MS: string;
	MAIL_FROM: string;
	MAIL_TO: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./monitor");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TARGET_URL" | "MONITOR_KEY" | "MODE" | "DRILL_START_MS" | "MAIL_FROM" | "MAIL_TO">> {}
}
