apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-doc-api
spec:
  template:
    spec:
      imagePullSecrets: [{name: enterprise-doc-registry}]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-doc-worker
spec:
  template:
    spec:
      imagePullSecrets: [{name: enterprise-doc-registry}]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-doc-consumer
spec:
  template:
    spec:
      imagePullSecrets: [{name: enterprise-doc-registry}]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-doc-web
spec:
  template:
    spec:
      imagePullSecrets: [{name: enterprise-doc-registry}]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: enterprise-doc-migrate
spec:
  template:
    spec:
      imagePullSecrets: [{name: enterprise-doc-registry}]
