apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: enterprise-doc-agent-staging
resources:
  - ../../base
  - ingress.yaml
  - web-ingress-policy.yaml
patches:
  - path: replicas-patch.yaml
  - path: configmap-patch.yaml
  - path: image-pull-secret-patch.yaml
images:
  - name: enterprise-doc/api
    newName: registry.example.invalid/enterprise-doc/api
    digest: sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  - name: enterprise-doc/worker
    newName: registry.example.invalid/enterprise-doc/worker
    digest: sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  - name: enterprise-doc/consumer
    newName: registry.example.invalid/enterprise-doc/consumer
    digest: sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
  - name: enterprise-doc/web
    newName: registry.example.invalid/enterprise-doc/web
    digest: sha256:dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
