apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-doc-api
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-doc-worker
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-doc-consumer
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-doc-web
spec:
  replicas: 1
