apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: enterprise-doc-web-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: enterprise-doc-web
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - {protocol: TCP, port: 8080}
