const UNAVAILABLE = 'Mail service unavailable';

/** @param {unknown} value @returns {value is string} */
function isSecret(value) {
  return typeof value === 'string' && /^[!-~]{32,}$/.test(value);
}

/** @param {unknown} value @returns {string[] | null} */
function secretList(value) {
  if (typeof value !== 'string') return null;
  try {
    const parsed = JSON.parse(value);
    return Array.isArray(parsed) && parsed.length > 0 && parsed.every(isSecret)
      ? parsed : null;
  } catch {
    return null;
  }
}

/** @param {Env} env */
function configured(env) {
  const site = secretList(env.PASSWORDS);
  const admin = secretList(env.ADMIN_PASSWORDS);
  if (!site || !admin || !isSecret(env.JWT_SECRET)) return false;
  if (![undefined, false, 'false'].includes(env.DISABLE_ADMIN_PASSWORD_CHECK)) return false;
  const secrets = [...site, ...admin, env.JWT_SECRET];
  return new Set(secrets).size === secrets.length;
}

function unavailable() {
  return new Response(UNAVAILABLE, {
    status: 503,
    headers: { 'Cache-Control': 'no-store', 'Content-Type': 'text/plain; charset=utf-8' },
  });
}

/**
 * Validate configuration before either public handler, including static assets.
 * Authentication and mailbox storage remain owned by the pinned upstream.
 * Env and platform handler types are generated by Wrangler during the build.
 * @param {Required<Pick<ExportedHandler<Env>, 'fetch' | 'email'>>} upstream
 * @returns {Required<Pick<ExportedHandler<Env>, 'fetch' | 'email'>>}
 */
export function createPrivateMailHandler(upstream) {
  return {
    async fetch(request, env, ctx) {
      if (!configured(env)) return unavailable();
      try {
        const response = await upstream.fetch(request, env, ctx);
        if (response.status < 500) return response;
        await response.body?.cancel();
      } catch {
        // Do not expose provider exceptions or identity email details.
      }
      return unavailable();
    },
    async email(message, env, ctx) {
      if (!configured(env)) {
        message.setReject(UNAVAILABLE);
        return;
      }
      try {
        await upstream.email(message, env, ctx);
      } catch {
        message.setReject(UNAVAILABLE);
      }
    },
  };
}
