apiVersion: v1
kind: Service
metadata:
  name: enterprise-doc-api
spec:
  selector:
    app.kubernetes.io/name: enterprise-doc-api
  ports:
    - {name: http, port: 8000, targetPort: http}
---
apiVersion: v1
kind: Service
metadata:
  name: enterprise-doc-worker
spec:
  selector:
    app.kubernetes.io/name: enterprise-doc-worker
  ports:
    - {name: probe, port: 8081, targetPort: probe}
---
apiVersion: v1
kind: Service
metadata:
  name: enterprise-doc-consumer
spec:
  selector:
    app.kubernetes.io/name: enterprise-doc-consumer
  ports:
    - {name: metrics, port: 8082, targetPort: metrics}
---
apiVersion: v1
kind: Service
metadata:
  name: enterprise-doc-web
spec:
  selector:
    app.kubernetes.io/name: enterprise-doc-web
  ports:
    - {name: http, port: 8080, targetPort: http}
