import type { Locale } from "../i18n";
import type { ResponseStatus } from "./api";

const zh = {
  title: "售前响应", summary: "把客户要求与企业资料逐条对照，核查证据后再交付。", newPacket: "新建响应表", documents: "上传与管理资料", recent: "我的响应表", empty: "还没有响应表。选择资料，开始第一份响应。", loading: "正在加载…", refresh: "刷新", login: "请先在资料页连接当前企业会话。", showcase: "售前工作台需要当前企业会话，展示模式不生成响应。",
  name: "响应表名称", namePlaceholder: "例如：华东企业版采购响应", sources: "1. 选择资料版本", sourceHelp: "最多 6 份。仅显示你有权访问且已处理完成的资料。", noSources: "还没有就绪资料，请先上传并等待处理完成。", scope: "资料适用范围", scopePlaceholder: "例如：本次采购采用企业版，部署在华东区域", confirmSources: "我已确认所选版本适用于本次客户要求", requirements: "2. 填写客户要求", requirementsHelp: "每行一条，最多 12 条；可用制表符在行末附上原文位置。保存后要求与资料版本固定。", requirementsPlaceholder: "日志需保留不少于 180 天\n应支持客户自行管理加密密钥", create: "保存响应表", createHelp: "先保存，再逐条生成。模型草稿需要人工核对。", invalid: "请填写名称、适用范围和 1–12 条要求，选择 1–6 份资料，并确认适用版本。", invalidLength: "每条要求最多 2000 字，原文位置最多 300 字。",
  generateAll: "生成待处理要求", generating: "正在生成", generate: "生成响应", retry: "重试本条", pending: "待生成", failed: "生成失败", waiting: "生成中，请稍后刷新", reviewed: "已复核", unreviewed: "待复核", complete: "已保存", exportDraft: "导出草稿 CSV", exportReviewed: "导出已复核 CSV", progress: "条已复核", sourceSnapshot: "本表资料版本", frozen: "要求与资料版本已固定。需要更换资料时，请新建响应表。", stale: "资料已变化，请新建响应表", rowDetail: "查看证据与复核", evidence: "原文证据", noEvidence: "尚无可引用的证据，请补充资料。", retrievalNotice: "基于有限召回片段生成，未命中不代表资料中不存在。", truncated: "部分片段已按长度或数量限制截取，请复核完整原文。", conditions: "未满足条件", missing: "待补材料", response: "响应文案", original: "原模型草稿", reviewTitle: "逐行复核", status: "判断", note: "复核备注", saveReview: "保存复核", reviewHelp: "确认文案、条件和证据后保存。原模型草稿会保留，人工修改不会覆盖它。", history: "复核历史", reviewer: "复核人", location: "原文位置", page: "页", offsets: "字符范围", version: "版本", applicable: "适用范围", requestId: "请求编号", error: "操作未完成，请刷新后重试。", rowError: "本条未生成可用响应，失败记录已保存。", modelTimeout: "等待模型响应超时，应用未保存本条结果。提供商仍可能完成并计费；重试会发起一次新请求。", attempts: "次生成尝试", draftOnly: "未复核草稿仅供内部核查。全部复核后可导出已复核版本。", sourceUnavailable: "资料不可访问或已变化，请刷新资料并新建响应表。", reset: "返回新建响应表", none: "无", reviewInvalid: "请检查文案、条件与待补材料；有条件支持需填写条件，证据不足需填写待补材料。",
};
const en: typeof zh = {
  title: "Presales responses", summary: "Match customer requirements to company sources, then verify the evidence before delivery.", newPacket: "New response sheet", documents: "Upload and manage sources", recent: "My response sheets", empty: "No response sheets yet. Choose sources to get started.", loading: "Loading…", refresh: "Refresh", login: "Connect your company session on the Documents page first.", showcase: "Presales requires a company session. Showcase mode does not generate responses.",
  name: "Response sheet name", namePlaceholder: "For example: Enterprise procurement response", sources: "1. Choose source versions", sourceHelp: "Up to 6 ready versions that you are authorized to access.", noSources: "No ready sources. Upload documents and wait for processing.", scope: "Source applicability", scopePlaceholder: "For example: Enterprise edition, East China deployment", confirmSources: "I confirm that these versions apply to the customer requirements", requirements: "2. Enter customer requirements", requirementsHelp: "One per line, up to 12. Add a tab followed by the source location if needed. Sources and requirements are fixed after saving.", requirementsPlaceholder: "Retain audit logs for at least 180 days\nSupport customer-managed encryption keys", create: "Save response sheet", createHelp: "Save first, then generate each response. Model drafts require review.", invalid: "Enter a name, scope and 1–12 requirements, select 1–6 sources and confirm their applicability.", invalidLength: "Each requirement is limited to 2000 characters and each location to 300.",
  generateAll: "Generate pending responses", generating: "Generating", generate: "Generate response", retry: "Retry this row", pending: "Pending", failed: "Generation failed", waiting: "Generating. Refresh shortly.", reviewed: "Reviewed", unreviewed: "Needs review", complete: "Saved", exportDraft: "Export draft CSV", exportReviewed: "Export reviewed CSV", progress: "rows reviewed", sourceSnapshot: "Source versions for this sheet", frozen: "Requirements and source versions are fixed. Create a new sheet to use different sources.", stale: "Sources changed; create a new sheet", rowDetail: "Evidence and review", evidence: "Source evidence", noEvidence: "No evidence to cite. Please supply the missing sources.", retrievalNotice: "Generated from limited retrieved passages. No match does not prove absence.", truncated: "Some passages were shortened or omitted by retrieval limits. Verify the original sources.", conditions: "Unmet conditions", missing: "Missing information", response: "Response", original: "Original model draft", reviewTitle: "Review this row", status: "Assessment", note: "Review note", saveReview: "Save review", reviewHelp: "Confirm the response, conditions and evidence. The original model draft is preserved.", history: "Review history", reviewer: "Reviewer", location: "Requirement location", page: "Page", offsets: "Character range", version: "Version", applicable: "Applicability", requestId: "Request ID", error: "The operation did not finish. Refresh and try again.", rowError: "No usable response was generated. The failure record was saved.", modelTimeout: "Timed out waiting for the model; no result was saved for this row. The provider may still complete and charge for it. Retrying sends a new request.", attempts: "generation attempts", draftOnly: "Unreviewed drafts are for internal checking. Review every row before exporting the reviewed version.", sourceUnavailable: "Sources changed or are unavailable. Refresh the sources and create a new sheet.", reset: "Back to new response sheet", none: "None", reviewInvalid: "Check the response, conditions and missing information. Conditional responses need conditions; insufficient evidence needs follow-up information.",
};
export function presalesCopy(locale: Locale) { return locale === "zh" ? zh : en; }
export function statusLabel(status: ResponseStatus, locale: Locale): string {
  const labels = { supported: ["支持", "Supported"], conditional: ["有条件支持", "Conditional"], contradicted: ["不满足", "Not met"], insufficient_evidence: ["证据不足", "Insufficient evidence"], conflicting_evidence: ["证据冲突", "Conflicting evidence"] };
  return labels[status][locale === "zh" ? 0 : 1];
}
