apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-doc-api
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-read-packages
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-doc-worker
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-read-packages

