apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-doc-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: api
          readinessProbe:
            periodSeconds: 20
            timeoutSeconds: 20
          resources:
            requests: {cpu: 75m, memory: 128Mi}
            limits: {cpu: 400m, memory: 224Mi}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-doc-worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: worker
          readinessProbe:
            periodSeconds: 30
            timeoutSeconds: 70
          startupProbe:
            failureThreshold: 60
          resources:
            requests: {cpu: 50m, memory: 128Mi}
            limits: {cpu: 400m, memory: 256Mi}

