apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: enterprise-doc-agent-staging
resources:
  - ../tiny-single-node
  - ../../../observability
patches:
  - path: resources-patch.yaml
  - path: replicas-patch.yaml
  - path: namespace-profile-patch.yaml
